# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=128),
        ),
    ]
