# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('darasa', '0002_auto_20160927_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='modeified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 9, 27, 13, 46, 29, 553300, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
