# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darasa', '0003_auto_20160927_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='modeified_at',
            new_name='modified_at',
        ),
    ]
