# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darasa', '0006_auto_20161007_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='owner',
            new_name='teacher',
        ),
    ]
